name: Test pipeline

on:
  push:

jobs:
  jar_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # sets up jdk
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8.0.232

      # Builds application
      - name: Build application
        run: |
          mvn package -DskipTests=true

      # Creates release zip
      - name: Create release zip
        run: |
          cp target/backup-export.jar .
          zip -r backup-export.zip backup-export.jar libs README.md
          ls
